platform :ios, "8.0"
use_frameworks!

workspace "xxxx"

xcodeproj "sited/sited.xcodeproj"

target:sited do
    pod "STHTTPRequest", "~> 1.1"
    pod "SWXMLHash", "~> 2.0.2"
    xcodeproj "sited/sited.xcodeproj"
end
